name: chatapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/foods.png
    - images/fruits.png
    - images/juices.png
    - images/vegetables.png
    - images/piazza_margherita.png
    - images/cheeseburger.png
    - images/caesar_salad.png
    - images/pasta_carbonara.png
    - images/grilled_salmon.png
    - images/tacos.png
    - images/sushi_platter.png
    - images/fried_chicken.png
    - images/steak.png
    - images/veggie_stir_fry.png
    - images/hamburger.png
    - images/pizza.png
    - images/chicken_pasta.png
    - images/pizza_tomato.png
    - images/vegan_pizza.png
    - images/othersushi.png
    - images/bolognese.png
    - images/sushisa.png
    - images/sushi_platter.png
    - images/meat.png
    - images/tacos.png
    - images/sushi.png
    - images/salad.png
    - images/cake-slice.png
    - images/pizza_chicken.png
    - images/hambur.png
    - images/lemon.png
    - images/lemonjuice.png
    - images/orange.png
    - images/orangejuice.png
    - images/strawberry.png
    - images/strawberryjuice.png
    - images/apple.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
